module Gio.StaticResource;

import GLib.c.functions;
import Gid.Gid;
import Gio.Resource;
import Gio.Types;
import Gio.c.functions;
import Gio.c.types;

/**
 * #GStaticResource is an opaque data structure and can only be accessed
 * using the following functions.
 */
class StaticResource
{
  GStaticResource cInstance;

  this(void* ptr, bool ownedRef = false)
  {
    if (!ptr)
      throw new GidConstructException("Null instance pointer for Gio.StaticResource");

    cInstance = *cast(GStaticResource*)ptr;

    if (ownedRef)
      g_free(ptr);
  }

  T* cPtr(T)()
  if (is(T == GStaticResource))
  {
    return cast(T*)&cInstance;
  }

  /**
   * Finalized a GResource initialized by g_static_resource_init().
   *
   * This is normally used by code generated by
   * [glib-compile-resources][glib-compile-resources]
   * and is not typically used by other code.
   */
  void fini()
  {
    g_static_resource_fini(cPtr!GStaticResource);
  }

  /**
   * a #GResource
   */
  Resource getResource()
  {
    GResource* _cretval;
    _cretval = g_static_resource_get_resource(cPtr!GStaticResource);
    Resource _retval = new Resource(cast(GResource*)_cretval, false);
    return _retval;
  }

  /**
   * Initializes a GResource from static data using a
   * GStaticResource.
   *
   * This is normally used by code generated by
   * [glib-compile-resources][glib-compile-resources]
   * and is not typically used by other code.
   */
  void init_()
  {
    g_static_resource_init(cPtr!GStaticResource);
  }
}
